/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiAcademyRouteImport } from './routes/ai-academy'
import { Route as AiDevelopmentRouteImport } from './routes/ai-development'
import { Route as AiOperatingSystemRouteImport } from './routes/ai-operating-system'
import { Route as AiRoadmapRouteImport } from './routes/ai-roadmap'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAcademyRoute = AiAcademyRouteImport.update({
  id: '/ai-academy',
  path: '/ai-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDevelopmentRoute = AiDevelopmentRouteImport.update({
  id: '/ai-development',
  path: '/ai-development',
  getParentRoute: () => rootRouteImport,
} as any)
const AiOperatingSystemRoute = AiOperatingSystemRouteImport.update({
  id: '/ai-operating-system',
  path: '/ai-operating-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoadmapRoute = AiRoadmapRouteImport.update({
  id: '/ai-roadmap',
  path: '/ai-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-academy': typeof AiAcademyRoute
  '/ai-development': typeof AiDevelopmentRoute
  '/ai-operating-system': typeof AiOperatingSystemRoute
  '/ai-roadmap': typeof AiRoadmapRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-academy': typeof AiAcademyRoute
  '/ai-development': typeof AiDevelopmentRoute
  '/ai-operating-system': typeof AiOperatingSystemRoute
  '/ai-roadmap': typeof AiRoadmapRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-academy': typeof AiAcademyRoute
  '/ai-development': typeof AiDevelopmentRoute
  '/ai-operating-system': typeof AiOperatingSystemRoute
  '/ai-roadmap': typeof AiRoadmapRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-academy'
    | '/ai-development'
    | '/ai-operating-system'
    | '/ai-roadmap'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-academy'
    | '/ai-development'
    | '/ai-operating-system'
    | '/ai-roadmap'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-academy'
    | '/ai-development'
    | '/ai-operating-system'
    | '/ai-roadmap'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAcademyRoute: typeof AiAcademyRoute
  AiDevelopmentRoute: typeof AiDevelopmentRoute
  AiOperatingSystemRoute: typeof AiOperatingSystemRoute
  AiRoadmapRoute: typeof AiRoadmapRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-academy': {
      id: '/ai-academy'
      path: '/ai-academy'
      fullPath: '/ai-academy'
      preLoaderRoute: typeof AiAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-development': {
      id: '/ai-development'
      path: '/ai-development'
      fullPath: '/ai-development'
      preLoaderRoute: typeof AiDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-operating-system': {
      id: '/ai-operating-system'
      path: '/ai-operating-system'
      fullPath: '/ai-operating-system'
      preLoaderRoute: typeof AiOperatingSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-roadmap': {
      id: '/ai-roadmap'
      path: '/ai-roadmap'
      fullPath: '/ai-roadmap'
      preLoaderRoute: typeof AiRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAcademyRoute: AiAcademyRoute,
  AiDevelopmentRoute: AiDevelopmentRoute,
  AiOperatingSystemRoute: AiOperatingSystemRoute,
  AiRoadmapRoute: AiRoadmapRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
